import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const base=process.env.DUPRVISION_UI_URL||'http://127.0.0.1:3017';
assert.equal(new URL(base).hostname,'127.0.0.1');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try {
  const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/Chicago',locale:'en-US'});
  const page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);
  await page.locator('#email').fill('qa-local@example.test');
  await page.locator('#password').fill('local-ui-test-2026');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.locator('[data-page="schedule"]').first().waitFor();
  await page.screenshot({path:'/tmp/duprvision-overview-calendar-refined.png',fullPage:true});
  await page.getByRole('button',{name:'Events',exact:true}).click();
  await page.getByRole('button',{name:'New event',exact:true}).click();
  await page.getByRole('button',{name:/Play session/}).click();
  assert.equal(await page.locator('input[name="visibility"][value="private"]').isChecked(),true);
  assert.equal(await page.getByRole('dialog').locator('[placeholder]').count(),0);
  assert.equal((await page.getByRole('dialog').innerText()).includes('optional'),false);
  assert.equal((await page.getByRole('dialog').innerText()).includes('America/Chicago'),false);
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  const prior=await page.request.get(base+'/api/schedule?'+new URLSearchParams({start:new Date().toISOString(),end:new Date(Date.now()+30*86400000).toISOString(),view:'mine'}));
  for(const event of (await prior.json()).events)await page.request.delete(base+'/api/schedule/'+event.id);
  await page.request.put(base+'/api/me',{data:{display_name:'Jordan Ellis',discoverable:true}});
  await page.reload();
  await page.locator('.nav-item[data-page="schedule"]').click();
  await page.getByRole('group',{name:'Play views'}).waitFor();
  await page.getByRole('button',{name:'New event',exact:true}).click();
  await page.getByRole('button',{name:/Play session/}).click();
  await page.getByRole('button',{name:'Enter manually',exact:true}).click();
  await page.locator('#plan-location').fill('The Picklr Lewisville');
  await page.locator('#plan-address').fill('Lewisville, TX');
  await page.locator('#plan-kind').selectOption('dupr_match');
  const date=new Date(Date.now()+2*86400000).toISOString().slice(0,10);
  await page.locator('#plan-start').fill(`${date}T18:00`);
  await page.locator('#plan-end').fill(`${date}T19:30`);
  await page.locator('#plan-note').fill('Court 4, doubles');
  await page.getByRole('dialog').getByRole('button',{name:'Add',exact:true}).click();
  await page.getByRole('heading',{name:'The Picklr Lewisville',exact:true}).waitFor();
  assert.match(await page.locator('.plan-row').innerText(),/6:00 PM/);
  assert.match(await page.getByRole('link',{name:'Open map'}).getAttribute('href'),/Lewisville/);
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  await page.locator('#plan-end').fill(`${date}T17:30`);
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByText('End time must be after the start, within 24 hours',{exact:true}).waitFor();
  assert.equal(await page.locator('#plan-location').inputValue(),'The Picklr Lewisville');
  await page.locator('#plan-end').fill(`${date}T20:00`);
  await page.locator('#plan-location').fill('The Picklr Lewisville North Courts');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByRole('heading',{name:'The Picklr Lewisville North Courts'}).waitFor();
  for(const width of [1440,768,390,320]) {
    await page.setViewportSize({width,height:900});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.screenshot({path:`/tmp/duprvision-calendar-${width}.png`,fullPage:true});
  }
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  assert.equal(await page.getByRole('dialog').evaluate(e=>e.scrollWidth>e.clientWidth),false);
  await page.screenshot({path:'/tmp/duprvision-calendar-editor.png'});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'/tmp/duprvision-calendar-editor-desktop.png'});
  await page.keyboard.press('Escape');
  await page.reload();
  await page.getByRole('heading',{name:'The Picklr Lewisville North Courts'}).waitFor();
  // A different account and time zone sees shared plans only after following.
  const followerContext=await browser.newContext({timezoneId:'America/Los_Angeles',locale:'en-US'}),follower=await followerContext.newPage();
  await follower.goto(base);
  await follower.locator('#email').fill('qa-follow@example.test');
  await follower.locator('#password').fill('local-ui-test-2026');
  await follower.getByRole('button',{name:'Sign in',exact:true}).click();
  await follower.locator('.nav-item[data-page="schedule"]').waitFor();
  await follower.request.post(base+'/api/players/qa-local/follow');
  await follower.locator('.nav-item[data-page="schedule"]').click();
  // Choose the month containing the fixture when running near a month boundary.
  await follower.evaluate(async date=>{const d=new Date(date+'T12:00:00');playing.month=new Date(d.getFullYear(),d.getMonth(),1);await loadSchedule();render();},date);
  await follower.getByRole('heading',{name:'The Picklr Lewisville North Courts'}).waitFor();
  assert.match(await follower.locator('.plan-row').innerText(),/4:00 PM/);
  assert.equal(await follower.getByRole('button',{name:'Edit',exact:true}).count(),0);
  await follower.locator('.nav-item[data-page="players"]').click();
  await follower.locator('[data-player="qa-local"]').click();
  await follower.getByRole('heading',{name:'Upcoming play'}).waitFor();
  await follower.getByRole('button',{name:'Following',exact:true}).click();
  await follower.getByRole('heading',{name:'The Picklr Lewisville North Courts'}).waitFor({state:'hidden'});
  assert.equal(await follower.getByRole('heading',{name:'The Picklr Lewisville North Courts'}).count(),0);
  await page.request.put(base+'/api/me',{data:{display_name:'Jordan Ellis',discoverable:false}});
  await page.reload();
  await page.locator('.nav-item[data-page="schedule"]').click();
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  assert.equal(await page.locator('input[name="visibility"][value="followers"]').isChecked(),true);
  page.once('dialog',dialog=>dialog.accept());
  await page.getByRole('button',{name:'Delete event',exact:true}).click();
  await page.getByText('No upcoming events.',{exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  console.log('Calendar passed: create/edit/delete, retained form errors, reload, map link, follower privacy, timezone conversion, profile plans and desktop/mobile layout.');
}finally{await browser.close();}
